# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  docs:
    dir: docs
    cmds:
      - pnpm install
      - pnpm start
    silent: true
  format:
    cmds:
      - ./gradlew ktlintFormat
    silent: true
  build:
    cmds:
      - ./gradlew build
    silent: true
  run:
    cmds:
      - ./gradlew runServer
    silent: true
  commit:
    cmds:
      - pnpm dlx git-cz

