name: Sync Labels

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/labels.json"

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2


      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm add -D @azu/github-label-setup

      - name: Remove color prefix
        run: sed -i 's/#//g' .github/labels.json

      - name: Run github-label-setup
        run: pnpm github-label-setup --token ${{ secrets.GITHUB_TOKEN }} --labels .github/labels.json
